import {
  AlignLeft,
  AtSign,
  Calendar,
  CalendarClock,
  CheckSquare,
  Clock,
  Files,
  Hash,
  Link2,
  ListChecks,
  LoaderCircle,
  MapPin,
  MousePointerClick,
  Phone,
  Search,
  Sigma,
  Text,
  Type,
  UserCircle,
  Users,
} from "lucide-react";
import type { PropertyType } from "./types";

export const PROPERTY_ICONS: Record<PropertyType, typeof Text> = {
  text: AlignLeft,
  title: Type,
  number: Hash,
  select: LoaderCircle,
  multi_select: ListChecks,
  status: LoaderCircle,
  checkbox: CheckSquare,
  person: Users,
  date: Calendar,
  created_time: Clock,
  created_by: UserCircle,
  last_edited_time: CalendarClock,
  last_edited_by: UserCircle,
  files: Files,
  url: Link2,
  email: AtSign,
  phone: Phone,
  relation: Link2,
  rollup: Search,
  formula: Sigma,
  id: Hash,
  button: MousePointerClick,
  place: MapPin,
};
