/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedCalendrierRouteImport } from './routes/_authenticated/calendrier'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedMailRouteImport } from './routes/_authenticated/mail'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedProjetsRouteImport } from './routes/_authenticated/projets'
import { Route as AuthenticatedTachesRouteImport } from './routes/_authenticated/taches'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendrierRoute = AuthenticatedCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMailRoute = AuthenticatedMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetsRoute = AuthenticatedProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTachesRoute = AuthenticatedTachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/mail': typeof AuthenticatedMailRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/projets': typeof AuthenticatedProjetsRoute
  '/taches': typeof AuthenticatedTachesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/mail': typeof AuthenticatedMailRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/projets': typeof AuthenticatedProjetsRoute
  '/taches': typeof AuthenticatedTachesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/calendrier': typeof AuthenticatedCalendrierRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/mail': typeof AuthenticatedMailRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/projets': typeof AuthenticatedProjetsRoute
  '/_authenticated/taches': typeof AuthenticatedTachesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/budget'
    | '/calendrier'
    | '/crm'
    | '/equipe'
    | '/mail'
    | '/parametres'
    | '/projets'
    | '/taches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/budget'
    | '/calendrier'
    | '/crm'
    | '/equipe'
    | '/mail'
    | '/parametres'
    | '/projets'
    | '/taches'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/budget'
    | '/_authenticated/calendrier'
    | '/_authenticated/crm'
    | '/_authenticated/equipe'
    | '/_authenticated/mail'
    | '/_authenticated/parametres'
    | '/_authenticated/projets'
    | '/_authenticated/taches'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendrier': {
      id: '/_authenticated/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AuthenticatedCalendrierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail': {
      id: '/_authenticated/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AuthenticatedMailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projets': {
      id: '/_authenticated/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof AuthenticatedProjetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taches': {
      id: '/_authenticated/taches'
      path: '/taches'
      fullPath: '/taches'
      preLoaderRoute: typeof AuthenticatedTachesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedCalendrierRoute: typeof AuthenticatedCalendrierRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedMailRoute: typeof AuthenticatedMailRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedProjetsRoute: typeof AuthenticatedProjetsRoute
  AuthenticatedTachesRoute: typeof AuthenticatedTachesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedCalendrierRoute: AuthenticatedCalendrierRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedMailRoute: AuthenticatedMailRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedProjetsRoute: AuthenticatedProjetsRoute,
  AuthenticatedTachesRoute: AuthenticatedTachesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
